import{a as v,S,i as a}from"./assets/vendor-5YrzWRhu.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const f of s.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&i(f)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const q="https://pixabay.com/api/",E="51734453-5d46674fc0c6d7944706aca6e";async function h(r,e=1,o=15){try{return(await v.get(q,{params:{key:E,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:o}})).data}catch(i){throw console.error("Error fetching images:",i),i}}const y=document.querySelector(".gallery"),g=document.querySelector(".loader"),p=document.querySelector(".load-more"),$=new S(".gallery a",{captionsData:"alt",captionDelay:250});function b(r){const e=r.map(o=>`
    <a href="${o.largeImageURL}" class="gallery-item">
      <div class="photo-card">
        <img class="photo-card-img" src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
        <ul class="info">
          <li><b>Likes:</b> ${o.likes}</li>
          <li><b>Views:</b> ${o.views}</li>
          <li><b>Comments:</b> ${o.comments}</li>
          <li><b>Downloads:</b> ${o.downloads}</li>
        </ul>
      </div>
    </a>
  `).join("");y.insertAdjacentHTML("beforeend",e),$.refresh()}function B(){y.innerHTML=""}function L(){g.classList.add("visible")}function m(){g.classList.remove("visible")}function w(){p.classList.remove("hidden")}function c(){p.classList.add("hidden")}const I=document.querySelector(".form"),M=document.querySelector(".load-more");let d="",n=1;const u=15;let l=0;async function P(r=!1){r&&(n=1,B()),L(),c();try{const e=await h(d,n,u);if(e.hits.length===0){a.error({title:"Error",message:"No images found. Try another query."}),m();return}l=e.totalHits,b(e.hits),l>n*u?w():(c(),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})),n===1&&a.success({title:"Success",message:`Found ${l} images.`})}catch(e){console.error(e),a.error({title:"Error",message:"Something went wrong. Try again later."})}finally{m()}}I.addEventListener("submit",async r=>{if(r.preventDefault(),d=r.currentTarget.elements["search-text"].value.trim(),!d){a.warning({title:"Warning",message:"Please enter a search query!"});return}await P(!0)});M.addEventListener("click",async()=>{n+=1,L(),c();try{const r=await h(d,n,u);b(r.hits);const e=document.querySelector(".gallery");if(e.firstElementChild){const{height:o}=e.firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}l>n*u?w():(c(),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}catch(r){console.error(r),a.error({title:"Error",message:"Something went wrong. Try again later."})}finally{m()}});
//# sourceMappingURL=index.js.map
