import{a as L,S as $,i as n}from"./assets/vendor-5YrzWRhu.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))i(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const h of s.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&i(h)}).observe(document,{childList:!0,subtree:!0});function r(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(o){if(o.ep)return;o.ep=!0;const s=r(o);fetch(o.href,s)}})();const P="https://pixabay.com/api/",x="51734453-5d46674fc0c6d7944706aca6e";async function v(e,t=1,r=15){try{return(await L.get(P,{params:{key:x,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:r}})).data}catch(i){throw console.error("Error fetching images:",i),i}}const S=document.querySelector(".gallery"),q=document.querySelector(".loader"),p=document.querySelector(".load-more"),B=new $(".gallery a",{captionsData:"alt",captionDelay:250});let d=1;const w=12;function m(e){const t=e.map(r=>`
    <a href="${r.largeImageURL}" class="gallery-item">
      <div class="photo-card">
        <img class="photo-card-img" src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
        <ul class="info">
          <li><b>Likes:</b> ${r.likes}</li>
          <li><b>Views:</b> ${r.views}</li>
          <li><b>Comments:</b> ${r.comments}</li>
          <li><b>Downloads:</b> ${r.downloads}</li>
        </ul>
      </div>
    </a>
  `).join("");S.insertAdjacentHTML("beforeend",t),B.refresh()}function E(){S.innerHTML=""}function b(){q.classList.add("visible")}function u(){q.classList.remove("visible")}function y(){p.classList.remove("hidden")}function c(){p.classList.add("hidden")}function I(e){return new Promise(t=>setTimeout(t,e))}async function T(e=1){b(),c();try{const r=await(await fetch(`https://pixabay.com/api/?key=51734453-5d46674fc0c6d7944706aca6e&q=flowers&page=${e}&per_page=${w}`)).json();return await I(5e3),r.hits}catch(t){return console.error(t),[]}finally{u()}}async function M(){E(),d=1;const e=await T(d);m(e),e.length===w&&y()}async function _(){d+=1;const e=await T(d);m(e),e.length<w?c():y()}p.addEventListener("click",_);M();const z=document.querySelector(".form"),A=document.querySelector(".load-more");document.querySelector(".loader");let f="",a=1;const g=15;let l=0;async function O(e=!1){e&&(a=1),b(),c();try{const t=await v(f,a,g);if(t.hits.length===0){n.error({title:"Error",message:"No images found. Try another query."}),u();return}l=t.totalHits,a===1&&E(),m(t.hits),l>a*g?y():(c(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})),a===1&&n.success({title:"Success",message:`Found ${l} images.`})}catch(t){console.error(t),n.error({title:"Error",message:"Something went wrong. Try again later."})}finally{u()}}z.addEventListener("submit",async e=>{if(e.preventDefault(),f=e.currentTarget.elements["search-text"].value.trim(),!f){n.warning({title:"Warning",message:"Please enter a search query!"});return}await O(!0)});A.addEventListener("click",async()=>{a+=1,b(),c();try{const e=await v(f,a,g);m(e.hits);const t=document.querySelector(".gallery");if(t.firstElementChild){const{height:r}=t.firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}l>a*g?y():(c(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}catch(e){console.error(e),n.error({title:"Error",message:"Something went wrong. Try again later."})}finally{u()}});L.get("https://pixabay.com/api/?key=51734453-5d46674fc0c6d7944706aca6e&q=cat&image_type=photo&per_page=3").then(e=>{console.log("Axios працює:",e.data)}).catch(e=>{console.error("Помилка Axios:",e)});const C=document.querySelector(".loader");console.log(C?"Spinner працює ✅":"Spinner не знайдено ❌");try{n.success({title:"Test",message:"iziToast працює (консольно тест) 👍",timeout:1}),console.log("iziToast підключено ✅")}catch(e){console.log("iziToast не підключено ❌",e)}
//# sourceMappingURL=index.js.map
